# Generated by Django 5.0.3 on 2024-03-11 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('van_re', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardriver',
            name='endRoute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='end_route', to='van_re.locations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardriver',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cardriver',
            name='startRoute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='start_route', to='van_re.locations'),
            preserve_default=False,
        ),
    ]
