# Generated by Django 5.0.3 on 2024-03-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('van_re', '0005_alter_carreservation_number_of_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreservation',
            name='amont_to_pay',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
