# Generated by Django 5.0.1 on 2024-02-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
