# Generated by Django 5.0.3 on 2024-03-12 14:45

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Van_Seat_Reserve_Backend', '0003_payment_amount'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='vanreservation',
            name='van',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='van', to='Van_Seat_Reserve_Backend.vandriver'),
        ),
        migrations.AlterField(
            model_name='vanreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='Van_Seat_Reserve_Backend.vanreservation'),
        ),
    ]
